// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8EX_svubXlBwFxyHv61C5kaSsGc0-Gw',
    appId: '1:287135393502:web:6f9a814106f5e7b84f044f',
    messagingSenderId: '287135393502',
    projectId: 'robotreception-c2a36',
    authDomain: 'robotreception-c2a36.firebaseapp.com',
    databaseURL: 'https://robotreception-c2a36-default-rtdb.firebaseio.com',
    storageBucket: 'robotreception-c2a36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe-P4FMULGgbF-CFzhLSAc6pIkOL9RNUs',
    appId: '1:287135393502:android:d31648a8b4917d0f4f044f',
    messagingSenderId: '287135393502',
    projectId: 'robotreception-c2a36',
    databaseURL: 'https://robotreception-c2a36-default-rtdb.firebaseio.com',
    storageBucket: 'robotreception-c2a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNE22ruOOw8w7k6Dhlltg9p9WAFNW8J3c',
    appId: '1:287135393502:ios:798d0b80894b48154f044f',
    messagingSenderId: '287135393502',
    projectId: 'robotreception-c2a36',
    databaseURL: 'https://robotreception-c2a36-default-rtdb.firebaseio.com',
    storageBucket: 'robotreception-c2a36.appspot.com',
    iosBundleId: 'com.example.chatnous',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNE22ruOOw8w7k6Dhlltg9p9WAFNW8J3c',
    appId: '1:287135393502:ios:8d02c4d0738c0c444f044f',
    messagingSenderId: '287135393502',
    projectId: 'robotreception-c2a36',
    databaseURL: 'https://robotreception-c2a36-default-rtdb.firebaseio.com',
    storageBucket: 'robotreception-c2a36.appspot.com',
    iosBundleId: 'com.example.chatnous.RunnerTests',
  );
}
